# Generated by Django 4.1 on 2022-12-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='checkIn',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='checkOut',
            new_name='checkout',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='rentalId',
        ),
        migrations.AddField(
            model_name='reservations',
            name='rental_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='reservation.rental'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
