# Generated by Django 4.1.4 on 2022-12-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_checkin_reservations_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rental_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='reservation.rental'),
        ),
    ]
